# Generated by Django 3.0.8 on 2020-08-11 15:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Нежелательная ссылка',
                'verbose_name_plural': 'Нежелательные ссылки',
            },
        ),
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting', models.TextField(verbose_name='Настройка')),
                ('value', models.TextField(verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Глобальная настройка',
                'verbose_name_plural': 'Глобальные настройки',
            },
        ),
        migrations.CreateModel(
            name='Gratitudes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=32, verbose_name='Слово благодарности')),
            ],
            options={
                'verbose_name': 'Слово благодарности',
                'verbose_name_plural': 'Слова благодарности',
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=32)),
                ('messages_in_last_interval', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='GroupsBlacklist',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID Группы')),
                ('title', models.CharField(max_length=32, verbose_name='Название Группы')),
            ],
            options={
                'verbose_name': 'Заблокированная группа',
                'verbose_name_plural': 'Заблокированные группы',
            },
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID Пользователя')),
                ('username', models.CharField(blank=True, max_length=32, null=True, verbose_name='Имя пользователя')),
                ('private_chat_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Администратор',
                'verbose_name_plural': 'Администраторы',
            },
        ),
        migrations.CreateModel(
            name='Swearing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Нецензурное выражение',
                'verbose_name_plural': 'Нецензурные выражения',
            },
        ),
        migrations.CreateModel(
            name='Whitelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Допустимое слово',
                'verbose_name_plural': 'Допустимые слова',
            },
        ),
        migrations.CreateModel(
            name='ScheduledMessages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(verbose_name='Текст')),
                ('interval', models.DurationField(verbose_name='Интервал')),
                ('task_id', models.CharField(blank=True, max_length=32, verbose_name='Уникальный номер задачи')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='group.Groups', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Запланированное сообщение',
                'verbose_name_plural': 'Запланированные сообщения',
                'db_table': 'group_scheduled_messages',
            },
        ),
        migrations.CreateModel(
            name='GroupsLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField(verbose_name='ID Группы')),
                ('supergroup_id', models.IntegerField(blank=True, null=True, verbose_name='ID Группы')),
                ('group_title', models.CharField(max_length=32, verbose_name='Название Группы')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Запрос обработан?')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Добавлен')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_by', to='group.Members', verbose_name='Добавивший')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_by', to='group.Members', verbose_name='Оработавший')),
            ],
            options={
                'verbose_name': 'Запись об активации бота',
                'verbose_name_plural': 'Записи об активации бота',
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0, verbose_name='Рейтинг')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата вступления в группу')),
                ('mute_rating', models.IntegerField(default=0, verbose_name='Кол-во нарушений')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='group.Groups', verbose_name='Название чата')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='group.Members', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'unique_together': {('user', 'chat')},
            },
        ),
    ]
